/**
 * Auto-Memoize Hook
 *
 * Automatic memory saving based on content analysis.
 */

import { PostHookFunction, HookResult } from './index.js';
import { autoSaveContent, detectImportantContent, extractTitle } from '../automations/auto-save.js';
import { getDb } from '../storage/client.js';
import { memories } from '../storage/schema.js';

function tokenize(text: string): string[] {
  return text.toLowerCase().replace(/[^\w\sàâäéèêëïîôùûüç]/g, ' ').split(/\s+/).filter(w => w.length > 2);
}

function calculateSimilarity(text1: string, text2: string): number {
  const terms1 = new Set(tokenize(text1));
  const terms2 = new Set(tokenize(text2));
  const intersection = new Set([...terms1].filter(x => terms2.has(x)));
  const union = new Set([...terms1, ...terms2]);
  return union.size > 0 ? intersection.size / union.size : 0;
}

async function isDuplicate(content: string, threshold = 0.85): Promise<boolean> {
  const db = getDb();
  const recent = await db.query.memories.findMany({
    orderBy: { createdAt: 'desc' },
    limit: 50,
  });

  for (const mem of recent) {
    if (calculateSimilarity(content, mem.content) >= threshold) {
      return true;
    }
  }
  return false;
}

function extractText(result: unknown): string {
  if (typeof result === 'string') return result;
  if (result && typeof result === 'object') {
    if ('content' in result && Array.isArray(result.content)) {
      return result.content
        .filter((c: any) => c.type === 'text')
        .map((c: any) => c.text)
        .join('\n');
    }
  }
  return '';
}

export function createAutoMemoizeHook(): PostHookFunction {
  return async (result: HookResult) => {
    if (!result.success) return;

    const skipTools = ['auto_save_memory', 'add_memory', 'update_memory', 'list_memories', 'search', 'smart_search'];
    if (skipTools.includes(result.toolName)) return;

    const content = extractText(result.result);
    if (!content || content.length < 100) return;

    const detection = detectImportantContent(content);
    if (!detection.detected || detection.confidence < 0.7) return;

    const duplicate = await isDuplicate(content);
    if (duplicate) return;

    const title = extractTitle(content, detection);

    await autoSaveContent(content, {
      title,
      type: detection.type,
      metadata: {
        autoGenerated: true,
        confidence: detection.confidence,
      },
    });

    console.log(`[Auto-Memoize] Saved: ${title}`);
  };
}
