/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatsIndexRouteImport } from './routes/stats.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as SearchIndexRouteImport } from './routes/search.index'
import { Route as RelationshipsIndexRouteImport } from './routes/relationships.index'
import { Route as MemoriesIndexRouteImport } from './routes/memories.index'
import { Route as HelpIndexRouteImport } from './routes/help.index'
import { Route as CodebaseIndexRouteImport } from './routes/codebase.index'
import { Route as AutomationIndexRouteImport } from './routes/automation.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsIndexRoute = RelationshipsIndexRouteImport.update({
  id: '/relationships/',
  path: '/relationships/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesIndexRoute = MemoriesIndexRouteImport.update({
  id: '/memories/',
  path: '/memories/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodebaseIndexRoute = CodebaseIndexRouteImport.update({
  id: '/codebase/',
  path: '/codebase/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationIndexRoute = AutomationIndexRouteImport.update({
  id: '/automation/',
  path: '/automation/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automation': typeof AutomationIndexRoute
  '/codebase': typeof CodebaseIndexRoute
  '/help': typeof HelpIndexRoute
  '/memories': typeof MemoriesIndexRoute
  '/relationships': typeof RelationshipsIndexRoute
  '/search': typeof SearchIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/stats': typeof StatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automation': typeof AutomationIndexRoute
  '/codebase': typeof CodebaseIndexRoute
  '/help': typeof HelpIndexRoute
  '/memories': typeof MemoriesIndexRoute
  '/relationships': typeof RelationshipsIndexRoute
  '/search': typeof SearchIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/stats': typeof StatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automation/': typeof AutomationIndexRoute
  '/codebase/': typeof CodebaseIndexRoute
  '/help/': typeof HelpIndexRoute
  '/memories/': typeof MemoriesIndexRoute
  '/relationships/': typeof RelationshipsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/stats/': typeof StatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automation'
    | '/codebase'
    | '/help'
    | '/memories'
    | '/relationships'
    | '/search'
    | '/sessions'
    | '/settings'
    | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automation'
    | '/codebase'
    | '/help'
    | '/memories'
    | '/relationships'
    | '/search'
    | '/sessions'
    | '/settings'
    | '/stats'
  id:
    | '__root__'
    | '/'
    | '/automation/'
    | '/codebase/'
    | '/help/'
    | '/memories/'
    | '/relationships/'
    | '/search/'
    | '/sessions/'
    | '/settings/'
    | '/stats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationIndexRoute: typeof AutomationIndexRoute
  CodebaseIndexRoute: typeof CodebaseIndexRoute
  HelpIndexRoute: typeof HelpIndexRoute
  MemoriesIndexRoute: typeof MemoriesIndexRoute
  RelationshipsIndexRoute: typeof RelationshipsIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships/': {
      id: '/relationships/'
      path: '/relationships'
      fullPath: '/relationships'
      preLoaderRoute: typeof RelationshipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/': {
      id: '/memories/'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codebase/': {
      id: '/codebase/'
      path: '/codebase'
      fullPath: '/codebase'
      preLoaderRoute: typeof CodebaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/': {
      id: '/automation/'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationIndexRoute: AutomationIndexRoute,
  CodebaseIndexRoute: CodebaseIndexRoute,
  HelpIndexRoute: HelpIndexRoute,
  MemoriesIndexRoute: MemoriesIndexRoute,
  RelationshipsIndexRoute: RelationshipsIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
