/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestGuideIndexRouteImport } from './routes/test-guide/index'
import { Route as SearchIndexRouteImport } from './routes/search.index'
import { Route as RelationshipsIndexRouteImport } from './routes/relationships.index'
import { Route as MemoriesIndexRouteImport } from './routes/memories.index'
import { Route as ContextsIndexRouteImport } from './routes/contexts/index'
import { Route as AutomationIndexRouteImport } from './routes/automation.index'
import { Route as TestGuideCategoryRouteImport } from './routes/test-guide/$category'
import { Route as ContextsNewRouteImport } from './routes/contexts/new'
import { Route as ContextsIdRouteImport } from './routes/contexts/$id'
import { Route as TestGuideCategoryTestIdRouteImport } from './routes/test-guide/$category/$testId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestGuideIndexRoute = TestGuideIndexRouteImport.update({
  id: '/test-guide/',
  path: '/test-guide/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsIndexRoute = RelationshipsIndexRouteImport.update({
  id: '/relationships/',
  path: '/relationships/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesIndexRoute = MemoriesIndexRouteImport.update({
  id: '/memories/',
  path: '/memories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextsIndexRoute = ContextsIndexRouteImport.update({
  id: '/contexts/',
  path: '/contexts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationIndexRoute = AutomationIndexRouteImport.update({
  id: '/automation/',
  path: '/automation/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestGuideCategoryRoute = TestGuideCategoryRouteImport.update({
  id: '/test-guide/$category',
  path: '/test-guide/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextsNewRoute = ContextsNewRouteImport.update({
  id: '/contexts/new',
  path: '/contexts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextsIdRoute = ContextsIdRouteImport.update({
  id: '/contexts/$id',
  path: '/contexts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TestGuideCategoryTestIdRoute = TestGuideCategoryTestIdRouteImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => TestGuideCategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contexts/$id': typeof ContextsIdRoute
  '/contexts/new': typeof ContextsNewRoute
  '/test-guide/$category': typeof TestGuideCategoryRouteWithChildren
  '/automation': typeof AutomationIndexRoute
  '/contexts': typeof ContextsIndexRoute
  '/memories': typeof MemoriesIndexRoute
  '/relationships': typeof RelationshipsIndexRoute
  '/search': typeof SearchIndexRoute
  '/test-guide': typeof TestGuideIndexRoute
  '/test-guide/$category/$testId': typeof TestGuideCategoryTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contexts/$id': typeof ContextsIdRoute
  '/contexts/new': typeof ContextsNewRoute
  '/test-guide/$category': typeof TestGuideCategoryRouteWithChildren
  '/automation': typeof AutomationIndexRoute
  '/contexts': typeof ContextsIndexRoute
  '/memories': typeof MemoriesIndexRoute
  '/relationships': typeof RelationshipsIndexRoute
  '/search': typeof SearchIndexRoute
  '/test-guide': typeof TestGuideIndexRoute
  '/test-guide/$category/$testId': typeof TestGuideCategoryTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contexts/$id': typeof ContextsIdRoute
  '/contexts/new': typeof ContextsNewRoute
  '/test-guide/$category': typeof TestGuideCategoryRouteWithChildren
  '/automation/': typeof AutomationIndexRoute
  '/contexts/': typeof ContextsIndexRoute
  '/memories/': typeof MemoriesIndexRoute
  '/relationships/': typeof RelationshipsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/test-guide/': typeof TestGuideIndexRoute
  '/test-guide/$category/$testId': typeof TestGuideCategoryTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contexts/$id'
    | '/contexts/new'
    | '/test-guide/$category'
    | '/automation'
    | '/contexts'
    | '/memories'
    | '/relationships'
    | '/search'
    | '/test-guide'
    | '/test-guide/$category/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contexts/$id'
    | '/contexts/new'
    | '/test-guide/$category'
    | '/automation'
    | '/contexts'
    | '/memories'
    | '/relationships'
    | '/search'
    | '/test-guide'
    | '/test-guide/$category/$testId'
  id:
    | '__root__'
    | '/'
    | '/contexts/$id'
    | '/contexts/new'
    | '/test-guide/$category'
    | '/automation/'
    | '/contexts/'
    | '/memories/'
    | '/relationships/'
    | '/search/'
    | '/test-guide/'
    | '/test-guide/$category/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContextsIdRoute: typeof ContextsIdRoute
  ContextsNewRoute: typeof ContextsNewRoute
  TestGuideCategoryRoute: typeof TestGuideCategoryRouteWithChildren
  AutomationIndexRoute: typeof AutomationIndexRoute
  ContextsIndexRoute: typeof ContextsIndexRoute
  MemoriesIndexRoute: typeof MemoriesIndexRoute
  RelationshipsIndexRoute: typeof RelationshipsIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  TestGuideIndexRoute: typeof TestGuideIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-guide/': {
      id: '/test-guide/'
      path: '/test-guide'
      fullPath: '/test-guide'
      preLoaderRoute: typeof TestGuideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships/': {
      id: '/relationships/'
      path: '/relationships'
      fullPath: '/relationships'
      preLoaderRoute: typeof RelationshipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/': {
      id: '/memories/'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contexts/': {
      id: '/contexts/'
      path: '/contexts'
      fullPath: '/contexts'
      preLoaderRoute: typeof ContextsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/': {
      id: '/automation/'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-guide/$category': {
      id: '/test-guide/$category'
      path: '/test-guide/$category'
      fullPath: '/test-guide/$category'
      preLoaderRoute: typeof TestGuideCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contexts/new': {
      id: '/contexts/new'
      path: '/contexts/new'
      fullPath: '/contexts/new'
      preLoaderRoute: typeof ContextsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contexts/$id': {
      id: '/contexts/$id'
      path: '/contexts/$id'
      fullPath: '/contexts/$id'
      preLoaderRoute: typeof ContextsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-guide/$category/$testId': {
      id: '/test-guide/$category/$testId'
      path: '/$testId'
      fullPath: '/test-guide/$category/$testId'
      preLoaderRoute: typeof TestGuideCategoryTestIdRouteImport
      parentRoute: typeof TestGuideCategoryRoute
    }
  }
}

interface TestGuideCategoryRouteChildren {
  TestGuideCategoryTestIdRoute: typeof TestGuideCategoryTestIdRoute
}

const TestGuideCategoryRouteChildren: TestGuideCategoryRouteChildren = {
  TestGuideCategoryTestIdRoute: TestGuideCategoryTestIdRoute,
}

const TestGuideCategoryRouteWithChildren =
  TestGuideCategoryRoute._addFileChildren(TestGuideCategoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContextsIdRoute: ContextsIdRoute,
  ContextsNewRoute: ContextsNewRoute,
  TestGuideCategoryRoute: TestGuideCategoryRouteWithChildren,
  AutomationIndexRoute: AutomationIndexRoute,
  ContextsIndexRoute: ContextsIndexRoute,
  MemoriesIndexRoute: MemoriesIndexRoute,
  RelationshipsIndexRoute: RelationshipsIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  TestGuideIndexRoute: TestGuideIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
